obj-m += kprobe_gup.o

all:
	make -C /mnt/c/Users/papu0/SW/dev_drv/WSL2-Linux-Kernel-linux-msft-wsl-5.15.167.4 M=$(shell pwd) modules

clean:
	make -C /mnt/c/Users/papu0/SW/dev_drv/WSL2-Linux-Kernel-linux-msft-wsl-5.15.167.4 M=$(shell pwd) clean
